"""add_session_id_to_bank_consents

Revision ID: 5fe5ea0841b4
Revises: 955ba4f854f8
Create Date: 2026-06-30 00:17:14.852413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fe5ea0841b4'
down_revision: Union[str, None] = '955ba4f854f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_consents', sa.Column('session_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bank_consents', 'session_id')
    # ### end Alembic commands ###
